/* =============================================
   DIVYA MANGALAM — DEITY DATABASE
   12 Major Gods with complete archana data
   ============================================= */

const GODS = [
  {
    id: 'ganesha',
    name: 'Lord Ganesha',
    sanskrit: 'श्री गणेशाय नमः',
    title: 'Vighnaharta – Remover of All Obstacles',
    emoji: '🐘',
    color: '#FF6F00',
    gradient: 'linear-gradient(135deg, #FF6F00, #FFB300)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Ganesha_Basohli_miniature_circa_1730_Dubost_p73.jpg/400px-Ganesha_Basohli_miniature_circa_1730_Dubost_p73.jpg',
    blessings: ['Remove Obstacles', 'Wisdom & Intelligence', 'New Beginnings', 'Success in Studies'],
    goodDays: ['Wednesday', 'Chaturthi (4th Tithi)', 'Sankashti Chaturthi'],
    goodNakshatras: ['Hasta', 'Ashwini', 'Pushya', 'Shravana'],
    avoidDays: [],
    avoidTithi: ['Ashtami', 'Chaturdashi'],
    primaryMantra: 'Om Gam Ganapataye Namaha',
    moola: 'ॐ गं गणपतये नमः',
    dhyana: 'OM Gajananaya Vidmahe Vakratundaya Dhimahi Tanno Danti Prachodayat',
    gayatri: 'Om Ekadantaya Vidmahe Vakratundaya Dhimahi Tanno Danti Prachodayat',
    offerings: [
      { name: 'Modak', icon: '🍮', mantra: 'Om Ganapataye Namaha — Modakam Samarpayami' },
      { name: 'Durva Grass', icon: '🌿', mantra: 'Om Gajanana Namaha — Darvam Samarpayami' },
      { name: 'Red Flowers', icon: '🌺', mantra: 'Om Vighnarajaya Namaha — Pushpam Samarpayami' },
      { name: 'Coconut', icon: '🥥', mantra: 'Om Lambodharaya Namaha — Narikela Samarpayami' },
      { name: 'Jaggery', icon: '🍯', mantra: 'Om Gauri Sutaya Namaha — Gudham Samarpayami' },
    ],
    ashtottara: [
      'Om Gajananaaya Namaha','Om Gaadhapataye Namaha','Om Herambaya Namaha',
      'Om Lambodharaya Namaha','Om Gajananaya Namaha','Om Vighnanaashanaya Namaha',
      'Om Vinayakaya Namaha','Om Dvaimaturaya Namaha','Om Agrajaya Namaha',
      'Om Parvaranandanaya Namaha','Om Vakratundaya Namaha','Om Shooraparaya Namaha',
    ],
    archanaSequence: [
      { step: 1, name: 'Achamana', icon: '💧', duration: 15, mantra: 'Om Keshavaya Namaha, Om Narayanaya Namaha, Om Madhavaya Namaha', meaning: 'Purification of self with water and mantra' },
      { step: 2, name: 'Sankalpa', icon: '🙏', duration: 30, mantra: 'Aum... (State your name, gotra, nakshatra) ...Ganesha prasada siddhyartham archana aham karishye', meaning: 'Sacred intention — declaring who you are and what you seek' },
      { step: 3, name: 'Dhyana', icon: '🧘', duration: 20, mantra: 'Shuklam Bharadaram Vishnum Shashivarnam Chaturbhujam, Prasanna Vadanam Dhyayet Sarva Vighnopashantaye', meaning: 'Meditative invocation of Lord Ganesha\'s divine form' },
      { step: 4, name: 'Avahana', icon: '🌸', duration: 15, mantra: 'Om Gam Ganapataye Namaha — Ganesha Avahayami Sthapayami', meaning: 'Inviting the Lord into the space of worship' },
      { step: 5, name: 'Pushparchana', icon: '🌺', duration: 40, mantra: 'Om Gam Ganapataye Namaha — Pushpam Samarpayami', meaning: 'Offering sacred flowers to the Lord' },
      { step: 6, name: 'Dhupa', icon: '🌫️', duration: 15, mantra: 'Vanaspati Rasodbhuto Gandhadhyo Gandha Uttama, Aghreya Sarvadevaanam Dhupa Ayam Pratigruhyatam', meaning: 'Offering sacred incense — purifying the space with fragrance' },
      { step: 7, name: 'Deepa', icon: '🪔', duration: 20, mantra: 'Saajyam Trivartisam Yuktam Vahnina Yojitam Maya, Deepam Gruhaana Devesha Trayataam Sankataat Prabho', meaning: 'Offering the sacred lamp — light that dispels all darkness' },
      { step: 8, name: 'Naivedya', icon: '🍮', duration: 20, mantra: 'Naivedyam Gruhyatam Deva Bhakti Me Achala Kuru, Ipsitam Me Varam Dehi Paradesi Para Bhava', meaning: 'Offering of sweet Modak — the Lord\'s favourite prasad' },
      { step: 9, name: 'Mangala Aarti', icon: '🔔', duration: 30, mantra: 'Jai Ganesh Jai Ganesh Jai Ganesh Deva, Mata Jaki Parvati Pita Mahadeva', meaning: 'Auspicious waving of the sacred lamp — the peak of worship' },
      { step: 10, name: 'Prasad & Visarjana', icon: '✨', duration: 15, mantra: 'Yantrasya Bhaktim Deepasya Dhupasya Pushpasya Namaskarasya Kshamisva Iti', meaning: 'Receiving blessings and respectfully concluding the ceremony' },
    ],
    famousTemples: ['Siddhivinayak Mumbai', 'Dagdusheth Ganpati Pune', 'Kanipakam Temple AP'],
  },

  {
    id: 'shiva',
    name: 'Lord Shiva',
    sanskrit: 'ॐ नमः शिवाय',
    title: 'Mahadeva – The Great God of Liberation',
    emoji: '🔱',
    color: '#1565C0',
    gradient: 'linear-gradient(135deg, #1565C0, #7B1FA2)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Shiva_Omkareshwar.jpg/400px-Shiva_Omkareshwar.jpg',
    blessings: ['Liberation (Moksha)', 'Health & Longevity', 'Destroy Negativity', 'Inner Peace'],
    goodDays: ['Monday', 'Pradosha (13th Tithi)', 'Maha Shivaratri', 'Ashtami'],
    goodNakshatras: ['Ardra', 'Uttara Bhadrapada', 'Krittika'],
    avoidDays: [],
    avoidTithi: [],
    primaryMantra: 'Om Namah Shivaya',
    moola: 'ॐ नमः शिवाय',
    dhyana: 'OM Tatpurushaya Vidmahe Mahadevaya Dhimahi Tanno Rudra Prachodayat',
    gayatri: 'Om Tatpurushaya Vidmahe Mahadevaya Dhimahi Tanno Rudra Prachodayat',
    offerings: [
      { name: 'Bilva Leaves', icon: '🍃', mantra: 'Om Namah Shivaya — Bilvapatram Samarpayami' },
      { name: 'Milk Abhishek', icon: '🥛', mantra: 'Om Shivaya Namaha — Dugdha Abhishekam Samarpayami' },
      { name: 'White Flowers', icon: '🌸', mantra: 'Om Mahadevaya Namaha — Shveta Pushpam Samarpayami' },
      { name: 'Vibhuti (Ash)', icon: '🌫️', mantra: 'Om Bhasmaabhutaya Namaha — Vibhutim Samarpayami' },
      { name: 'Rudraksha', icon: '📿', mantra: 'Om Rudrakshaya Namaha — Rudraksham Samarpayami' },
    ],
    ashtottara: [
      'Om Shivaya Namaha','Om Maheshvaraya Namaha','Om Shambhave Namaha',
      'Om Pinakine Namaha','Om Shashishekharaya Namaha','Om Vamadevaya Namaha',
      'Om Virupakshaya Namaha','Om Kapardine Namaha','Om Neelalohitaya Namaha',
      'Om Shankaraya Namaha','Om Shulapanaye Namaha','Om Khatvangine Namaha',
    ],
    archanaSequence: [
      { step: 1, name: 'Achamana', icon: '💧', duration: 15, mantra: 'Om Namah Shivaya — Achamanam Samarpayami', meaning: 'Purification with sacred water' },
      { step: 2, name: 'Sankalpa', icon: '🙏', duration: 30, mantra: '(Your name, gotra, nakshatra) ...Shiva prasada siddhyartham archana karishye', meaning: 'Sacred intention before Lord Shiva' },
      { step: 3, name: 'Dhyana', icon: '🧘', duration: 20, mantra: 'Dhyaayennityanm Mahesham Rajata Girinibham Charu Chandravataamsam', meaning: 'Meditating on Shiva\'s silver moonlit form' },
      { step: 4, name: 'Abhisheka', icon: '🥛', duration: 40, mantra: 'Om Namah Shivaya — Dugdha Abhishekam Samarpayami (Milk, Water, Honey, Curd, Ghee)', meaning: 'Sacred bathing of the Shivalinga with Panchamruta' },
      { step: 5, name: 'Bilva Archana', icon: '🍃', duration: 40, mantra: 'Tridalam Trigunakaram Trinetram Cha Triyayudham — Bilvapatram Samarpayami Namaha Shivaya', meaning: 'Offering 108 Bilva leaves — the most sacred offering to Shiva' },
      { step: 6, name: 'Deepa Aarti', icon: '🪔', duration: 20, mantra: 'Om Namah Shivaya — Deepam Samarpayami', meaning: 'Waving the sacred lamp before the Lord' },
      { step: 7, name: 'Maha Mrityunjaya', icon: '🔱', duration: 60, mantra: 'Om Tryambakam Yajaamahe Sugandhim Pushtivardhanam Urvarukamiva Bandhanaan Mrityor Muksheeya Maamrtaat', meaning: 'The great liberating mantra of Lord Shiva — protection from all suffering' },
      { step: 8, name: 'Visarjana', icon: '✨', duration: 15, mantra: 'Om Namah Shivaya — Shiva Shambho Mahadeva', meaning: 'Receiving Shiva\'s blessings of liberation and peace' },
    ],
    famousTemples: ['Kashi Vishwanath', 'Somnath Gujarat', 'Tiruvannamalai Tamil Nadu'],
  },

  {
    id: 'lakshmi',
    name: 'Maa Lakshmi',
    sanskrit: 'ॐ श्रीं महालक्ष्म्यै नमः',
    title: 'Goddess of Prosperity, Wealth & Auspiciousness',
    emoji: '🪷',
    color: '#C62828',
    gradient: 'linear-gradient(135deg, #C62828, #FF8F00)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Lakshmi_by_Raja_Ravi_Varma.jpg/400px-Lakshmi_by_Raja_Ravi_Varma.jpg',
    blessings: ['Wealth & Prosperity', 'Health', 'Beauty', 'Peace in Home', 'Good Fortune'],
    goodDays: ['Friday', 'Amavasya', 'Purnima', 'Diwali', 'Varalakshmi Vratam'],
    goodNakshatras: ['Rohini', 'Purva Phalguni', 'Purva Ashadha'],
    avoidDays: ['Sunday'],
    avoidTithi: [],
    primaryMantra: 'Om Shreem Hreem Shreem Kamale Kamalalaye Praseed Praseed',
    moola: 'ॐ श्रीं महालक्ष्म्यै नमः',
    dhyana: 'Om Mahalakshmyai Cha Vidmahe Vishnu Patnyai Cha Dhimahi Tanno Lakshmi Prachodayat',
    gayatri: 'Om Mahalakshmyai Vidmahe Vishnu Patnyai Dhimahi Tanno Lakshmi Prachodayat',
    offerings: [
      { name: 'Lotus Flowers', icon: '🪷', mantra: 'Om Shreem Mahalakshmyai Namaha — Pushpam Samarpayami' },
      { name: 'Kumkum', icon: '🔴', mantra: 'Om Hreem Mahalakshmyai Namaha — Kumkumam Samarpayami' },
      { name: 'Turmeric', icon: '🟡', mantra: 'Om Shreem Namaha — Haridraam Samarpayami' },
      { name: 'Sweet Rice', icon: '🍚', mantra: 'Om Mahalakshmyai Namaha — Sharkara Pongalam Samarpayami' },
      { name: 'Gold Coin', icon: '🪙', mantra: 'Om Dhanadayai Namaha — Svarnam Samarpayami' },
    ],
    ashtottara: [
      'Om Prakrityai Namaha','Om Vikrityai Namaha','Om Vidyaayai Namaha',
      'Om Sarvabhutahitapradaayai Namaha','Om Shradhaayai Namaha','Om Vibhutyai Namaha',
      'Om Surabhyai Namaha','Om Paramatmikaayai Namaha','Om Vaachae Namaha',
      'Om Padmaalayaayai Namaha','Om Padmaayai Namaha','Om Shuchaye Namaha',
    ],
    archanaSequence: [
      { step: 1, name: 'Kalasha Puja', icon: '🏺', duration: 20, mantra: 'Om Shreem Hreem Shreem — Kalasham Devim Avahayami', meaning: 'Invoking Maa Lakshmi into the sacred vessel' },
      { step: 2, name: 'Sankalpa', icon: '🙏', duration: 30, mantra: '(Name, gotra) ...Mahalakshmi prasada siddhyartham archana karishye', meaning: 'Setting sacred intention before the Goddess' },
      { step: 3, name: 'Dhyana', icon: '🧘', duration: 20, mantra: 'Ya Sa Padmasanasthaa Vipula Katitati Padmalaalaa Anantha, Sa Shri Vishnorvakshasthala Nitaratam Vashataam', meaning: 'Meditating on Goddess Lakshmi seated on the lotus' },
      { step: 4, name: 'Lotus Archana', icon: '🪷', duration: 40, mantra: 'Om Shreem Mahalakshmyai Namaha — Pushpam Samarpayami (108 times)', meaning: 'Offering 108 lotus petals to the Goddess' },
      { step: 5, name: 'Kumkuma Archana', icon: '🔴', duration: 30, mantra: 'Om Hreem Shreem Lakshmi Bhyo Namaha — Kumkumam Samarpayami', meaning: 'Sacred kumkum offering — invoking all eight forms of Lakshmi' },
      { step: 6, name: 'Lakshmi Stotra', icon: '📖', duration: 40, mantra: 'Namastestu Mahamaye Shri Peethe Sura Poojite, Shankha Chakra Gada Haste Mahalakshmi Namostute', meaning: 'Reciting the sacred Lakshmi Stotra' },
      { step: 7, name: 'Deepa Aarti', icon: '🪔', duration: 20, mantra: 'Om Jai Lakshmi Mata, Maiyya Jai Lakshmi Mata, Tumko Nishadin Sevat, Hari Vishnu Dhata', meaning: 'Waving the golden lamp before the Goddess of prosperity' },
      { step: 8, name: 'Prasad', icon: '✨', duration: 15, mantra: 'Om Shreem Mahalakshmyai Namaha — Prasadam Gruhana', meaning: 'Receiving Lakshmi\'s blessings of abundance and auspiciousness' },
    ],
    famousTemples: ['Tirupati Padmavathi', 'Kolhapur Mahalakshmi', 'Mahalakshmi Mumbai'],
  },

  {
    id: 'durga',
    name: 'Maa Durga',
    sanskrit: 'ॐ दुं दुर्गायै नमः',
    title: 'Durgati Nashini – Destroyer of All Evil',
    emoji: '⚔️',
    color: '#E53935',
    gradient: 'linear-gradient(135deg, #B71C1C, #E53935)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Durga_Puja_2012.jpg/400px-Durga_Puja_2012.jpg',
    blessings: ['Protection from Evil', 'Courage & Strength', 'Destroy Enemies', 'Victory'],
    goodDays: ['Tuesday', 'Friday', 'Navratri', 'Ashtami', 'Navami'],
    goodNakshatras: ['Mrigashira', 'Chitra', 'Jyeshtha'],
    avoidDays: [],
    avoidTithi: [],
    primaryMantra: 'Om Dum Durgaye Namaha',
    moola: 'ॐ दुं दुर्गायै नमः',
    dhyana: 'Om Katyayanyai Vidmahe Kanyakumari Dhimahi Tanno Durgih Prachodayat',
    gayatri: 'Om Katyayanyai Vidmahe Kanyakumari Dhimahi Tanno Durgih Prachodayat',
    offerings: [
      { name: 'Red Hibiscus', icon: '🌺', mantra: 'Om Durgaye Namaha — Rakta Pushpam Samarpayami' },
      { name: 'Sindoor', icon: '🔴', mantra: 'Om Chandikaye Namaha — Sindooram Samarpayami' },
      { name: 'Red Cloth', icon: '🟥', mantra: 'Om Katyayanyai Namaha — Vastra Samarpayami' },
      { name: 'Coconut', icon: '🥥', mantra: 'Om Mahishasura Mardinyai Namaha — Narikela Samarpayami' },
      { name: 'Paan (Betel)', icon: '🌿', mantra: 'Om Shaktaye Namaha — Tamboola Samarpayami' },
    ],
    ashtottara: [
      'Om Sativyai Namaha','Om Abhayayai Namaha','Om Omkarayai Namaha',
      'Om Jnanashaktidharayai Namaha','Om Chandikayai Namaha','Om Yoginayai Namaha',
      'Om Kalaratryai Namaha','Om Kaushikyai Namaha','Om Shivadutayai Namaha',
      'Om Mahishasuramardinyai Namaha','Om Sarvashaktimayai Namaha','Om Sarvamangalayai Namaha',
    ],
    archanaSequence: [
      { step: 1, name: 'Achamana', icon: '💧', duration: 15, mantra: 'Om Durgaye Namaha — Achamanam Samarpayami', meaning: 'Purification before approaching the fierce Goddess' },
      { step: 2, name: 'Sankalpa', icon: '🙏', duration: 30, mantra: '(Name, gotra) ...Durga Mata prasada siddhyartham archana karishye', meaning: 'Declaring intention before the Shakti' },
      { step: 3, name: 'Devi Dhyana', icon: '🧘', duration: 20, mantra: 'Ya Devi Sarvabhuteshu Shakti Rupena Sansthita, Namastasyai Namastasyai Namastasyai Namo Namaha', meaning: 'Meditating on Devi as the universal power in all beings' },
      { step: 4, name: 'Durga Saptashati Path', icon: '📿', duration: 60, mantra: 'Om Jayanti Mangala Kaali Bhadrakaali Kapalini, Durga Kshama Shivaa Dhatri Svaha Svadha Namostute', meaning: 'Reciting the Durga Saptashati — 700 verses of the Devi Mahatmyam' },
      { step: 5, name: 'Kumkuma Archana', icon: '🔴', duration: 40, mantra: 'Om Dum Durgaye Namaha — Kumkumam Samarpayami (108 times)', meaning: 'Offering 108 kumkum pushpa — invoking all nine forms of Durga' },
      { step: 6, name: 'Deepa Aarti', icon: '🪔', duration: 20, mantra: 'Jai Ambe Gauri, Maiyya Jai Shyama Gauri, Tumko Nishadin Dhyavat Hari Brahma Shivri', meaning: 'Waving the sacred lamp before the great warrior Goddess' },
      { step: 7, name: 'Visarjana', icon: '✨', duration: 15, mantra: 'Sarva Mangala Mangalye Shive Sarvaartha Saadhike, Sharanye Trayambake Gauri Naraayani Namostute', meaning: 'Receiving the Goddess\'s blessings of protection and victory' },
    ],
    famousTemples: ['Vaishno Devi Kashmir', 'Kamakhya Assam', 'Vindhyavasini UP'],
  },

  {
    id: 'hanuman',
    name: 'Lord Hanuman',
    sanskrit: 'ॐ हनुमते नमः',
    title: 'Sankata Mochan – Reliever of All Distress',
    emoji: '🙏',
    color: '#FF6F00',
    gradient: 'linear-gradient(135deg, #E65100, #FF8F00)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Hanuman_Ramayana.jpg/400px-Hanuman_Ramayana.jpg',
    blessings: ['Protection & Safety', 'Strength & Courage', 'Remove Fear', 'Devotion to Rama', 'Health'],
    goodDays: ['Tuesday', 'Saturday', 'Hanuman Jayanti', 'Purnima'],
    goodNakshatras: ['Swati', 'Vishakha', 'Anuradha'],
    avoidDays: [],
    avoidTithi: [],
    primaryMantra: 'Om Hanumate Namaha',
    moola: 'ॐ हनुमते नमः',
    dhyana: 'Om Aanjaneyaya Vidmahe Vayuputraya Dhimahi Tanno Hanuma Prachodayat',
    gayatri: 'Om Aanjaneyaya Vidmahe Vayuputraya Dhimahi Tanno Hanuma Prachodayat',
    offerings: [
      { name: 'Sindoor', icon: '🔴', mantra: 'Om Hanumate Namaha — Sindooram Samarpayami' },
      { name: 'Jasmine Oil', icon: '🌸', mantra: 'Om Vayu Putraya Namaha — Tailam Samarpayami' },
      { name: 'Tulsi', icon: '🌿', mantra: 'Om Anjaneyaya Namaha — Tulasi Samarpayami' },
      { name: 'Banana', icon: '🍌', mantra: 'Om Kapishaya Namaha — Kadali Phalam Samarpayami' },
      { name: 'Betel Nut', icon: '🟤', mantra: 'Om Sankatamochanaya Namaha — Tamboola Samarpayami' },
    ],
    ashtottara: [
      'Om Anjaneyaya Namaha','Om Mahaabalaya Namaha','Om Pavana Putraya Namaha',
      'Om Ramadutaya Namaha','Om Kesarinandanaya Namaha','Om Sitashokavinaashanaya Namaha',
      'Om Sugreeva Sachivaya Namaha','Om Pitaambara Dharaya Namaha','Om Vayu Putraya Namaha',
      'Om Deerghabahave Namaha','Om Sankata Mochanaya Namaha','Om Buddhimataama Varisthaaya Namaha',
    ],
    archanaSequence: [
      { step: 1, name: 'Achamana', icon: '💧', duration: 15, mantra: 'Om Hanumate Namaha — Achamanam Samarpayami', meaning: 'Purification before approaching the great devotee of Rama' },
      { step: 2, name: 'Sankalpa', icon: '🙏', duration: 30, mantra: '(Name, gotra) ...Hanuman prasada siddhyartham archana karishye', meaning: 'Sacred intention before Lord Hanuman' },
      { step: 3, name: 'Dhyana', icon: '🧘', duration: 20, mantra: 'Manojavam Maruta Tulya Vegam Jitendriyam Buddhimataam Varistham, Vaataatmajam Vaanara Yoota Mukhyam Shri Rama Dootam Sharanam Prapadye', meaning: 'Meditating on Hanuman — swift as the wind, master of senses' },
      { step: 4, name: 'Hanuman Chalisa', icon: '📖', duration: 120, mantra: 'Shri Guru Charan Saroj Raj Nij Manu Mukur Sudhar, Barnau Raghuvar Bimal Jasu Jo Dayaku Phal Char', meaning: 'Reciting the complete Hanuman Chalisa — 40 sacred verses' },
      { step: 5, name: 'Sindoor Archana', icon: '🔴', duration: 40, mantra: 'Om Hanumate Namaha — Sindooram Samarpayami (108 times)', meaning: 'Offering sindoor to Lord Hanuman — his most beloved offering' },
      { step: 6, name: 'Aarti', icon: '🪔', duration: 20, mantra: 'Aarti Kije Hanuman Lala Ki, Dushta Dalan Raghunath Kala Ki', meaning: 'Waving the sacred lamp before the great Hanuman' },
      { step: 7, name: 'Visarjana', icon: '✨', duration: 15, mantra: 'Om Hanumate Namaha — Shri Rama Jai Rama Jai Jai Rama', meaning: 'Receiving Hanuman\'s blessings of courage and protection' },
    ],
    famousTemples: ['Sankat Mochan Varanasi', 'Hanuman Garhi Ayodhya', 'Salasar Balaji Rajasthan'],
  },

  {
    id: 'vishnu',
    name: 'Lord Vishnu',
    sanskrit: 'ॐ नमो नारायणाय',
    title: 'Jagatpati – Preserver of the Universe',
    emoji: '🪷',
    color: '#1565C0',
    gradient: 'linear-gradient(135deg, #0D47A1, #1976D2)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Vishnu_Rig_Veda.jpg/400px-Vishnu_Rig_Veda.jpg',
    blessings: ['Preservation & Protection', 'Dharma', 'Marriage Blessings', 'Moksha', 'Peace'],
    goodDays: ['Thursday', 'Ekadashi', 'Vaikunta Ekadashi', 'Purnima'],
    goodNakshatras: ['Shravana', 'Uttara Phalguni', 'Punarvasu'],
    avoidDays: [],
    avoidTithi: ['Chaturdashi'],
    primaryMantra: 'Om Namo Narayanaya',
    moola: 'ॐ नमो नारायणाय',
    dhyana: 'Om Narayanaya Vidmahe Vasudevaya Dhimahi Tanno Vishnu Prachodayat',
    gayatri: 'Om Narayanaya Vidmahe Vasudevaya Dhimahi Tanno Vishnu Prachodayat',
    offerings: [
      { name: 'Tulsi Leaves', icon: '🌿', mantra: 'Om Vishnave Namaha — Tulasi Samarpayami' },
      { name: 'Yellow Flowers', icon: '🌼', mantra: 'Om Narayanaya Namaha — Pushpam Samarpayami' },
      { name: 'Panchamruta', icon: '🥛', mantra: 'Om Vasudevaya Namaha — Panchamrutam Samarpayami' },
      { name: 'Yellow Silk', icon: '🟡', mantra: 'Om Madhavaya Namaha — Vastram Samarpayami' },
      { name: 'Chandan', icon: '🟤', mantra: 'Om Govindaya Namaha — Chandanam Samarpayami' },
    ],
    ashtottara: [
      'Om Vishnave Namaha','Om Lakshmipate Namaha','Om Krishnaya Namaha',
      'Om Vaikunthaya Namaha','Om Garudadhvajaya Namaha','Om Parabrahmanaya Namaha',
      'Om Jagannathaya Namaha','Om Vasudevaya Namaha','Om Trivikramaya Namaha',
      'Om Damodaraya Namaha','Om Shridhara Namaha','Om Hrishikeshaya Namaha',
    ],
    archanaSequence: [
      { step: 1, name: 'Panchamruta Abhisheka', icon: '🥛', duration: 30, mantra: 'Om Namo Narayanaya — Panchamrutam Samarpayami', meaning: 'Bathing Lord Vishnu with the five sacred nectars' },
      { step: 2, name: 'Sankalpa', icon: '🙏', duration: 30, mantra: '(Name, gotra) ...Vishnu Narayana prasada siddhyartham archana karishye', meaning: 'Sacred intention before the Preserver of the Universe' },
      { step: 3, name: 'Tulsi Archana', icon: '🌿', duration: 40, mantra: 'Om Namo Narayanaya — Tulasim Samarpayami (108 times)', meaning: 'Offering Tulsi — the most sacred plant of Lord Vishnu' },
      { step: 4, name: 'Vishnu Sahasranama', icon: '📖', duration: 90, mantra: 'Shantaakaaram Bhujagashayanam Padmanabham Suresham', meaning: 'Reciting 1000 sacred names of Lord Vishnu' },
      { step: 5, name: 'Deepa Aarti', icon: '🪔', duration: 20, mantra: 'Om Jai Jagdish Hare, Swami Jai Jagdish Hare, Bhakta Jano Ke Sankat Das Jana Ke Sankat, Kshan Mein Dur Kare', meaning: 'Waving the lamp before the Lord of the Universe' },
      { step: 6, name: 'Visarjana', icon: '✨', duration: 15, mantra: 'Om Namo Narayanaya — Hari Hari Narayana', meaning: 'Receiving Vishnu\'s blessings of protection and liberation' },
    ],
    famousTemples: ['Tirupati Balaji', 'Ranganathaswamy Srirangam', 'Dwarkadhish Gujarat'],
  },

  {
    id: 'saraswati',
    name: 'Maa Saraswati',
    sanskrit: 'ॐ ऐं सरस्वत्यै नमः',
    title: 'Vak Devi – Goddess of Knowledge & Arts',
    emoji: '🎶',
    color: '#FFFFFF',
    gradient: 'linear-gradient(135deg, #E3F2FD, #1565C0)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Goddess_Saraswati_by_Raja_Ravi_Varma.jpg/400px-Goddess_Saraswati_by_Raja_Ravi_Varma.jpg',
    blessings: ['Education & Knowledge', 'Music & Arts', 'Eloquence', 'Exams & Studies', 'Creativity'],
    goodDays: ['Wednesday', 'Panchami', 'Vasanta Panchami', 'Vijayadashami'],
    goodNakshatras: ['Hasta', 'Ashlesha', 'Revati'],
    avoidDays: [],
    avoidTithi: [],
    primaryMantra: 'Om Aim Saraswatyai Namaha',
    moola: 'ॐ ऐं सरस्वत्यै नमः',
    dhyana: 'Om Sarasvatyai Vidmahe Brahmaputryai Dhimahi Tanno Devi Prachodayat',
    gayatri: 'Om Sarasvatyai Vidmahe Brahmaputryai Dhimahi Tanno Devi Prachodayat',
    offerings: [
      { name: 'White Flowers', icon: '🌸', mantra: 'Om Sarasvatyai Namaha — Shveta Pushpam Samarpayami' },
      { name: 'Books / Pen', icon: '📚', mantra: 'Om Vak Devyai Namaha — Pustakam Samarpayami' },
      { name: 'White Sweets', icon: '🍚', mantra: 'Om Veenavadinyai Namaha — Naivedyam Samarpayami' },
      { name: 'Akshamala', icon: '📿', mantra: 'Om Haamsavahinyai Namaha — Akshamalaam Samarpayami' },
      { name: 'Music Instrument', icon: '🎶', mantra: 'Om Saptasvara Rupayai Namaha — Veenam Samarpayami' },
    ],
    ashtottara: [
      'Om Sarasvatyai Namaha','Om Mahabhagayai Namaha','Om Vidyadayinyai Namaha',
      'Om Veenapanaye Namaha','Om Varadaayai Namaha','Om Pustakadhaarinyai Namaha',
      'Om Sarvadevastutaayai Namaha','Om Akshamalaadhaarayai Namaha','Om Mahaavidyaayai Namaha',
      'Om Sarvavijnaapradaayai Namaha','Om Haamsasanaayai Namaha','Om Vaakyai Namaha',
    ],
    archanaSequence: [
      { step: 1, name: 'Pustakapuja', icon: '📚', duration: 20, mantra: 'Om Sarasvatyai Namaha — Pustakam Pujayami', meaning: 'Placing books and instruments before the Goddess for her blessing' },
      { step: 2, name: 'Sankalpa', icon: '🙏', duration: 30, mantra: '(Name, gotra) ...Saraswati prasada siddhyartham archana karishye', meaning: 'Seeking the Goddess\'s blessings for knowledge and wisdom' },
      { step: 3, name: 'Dhyana', icon: '🧘', duration: 20, mantra: 'Ya Kundendu Tusharahara Dhavalaa Ya Shubhravasraavrita Ya Veenavara Dandamanditakara', meaning: 'Meditating on white-robed Saraswati with her divine Veena' },
      { step: 4, name: 'White Flower Archana', icon: '🌸', duration: 40, mantra: 'Om Aim Sarasvatyai Namaha — Pushpam Samarpayami (108 times)', meaning: 'Offering 108 white flowers — invoking all eight forms of Saraswati' },
      { step: 5, name: 'Aksharabhyasa', icon: '✍️', duration: 30, mantra: 'Om Aim Hreem Kleem Sarasvatyai Namaha — Aksharabhyasam Samarpayami', meaning: 'Writing the first letters as an offering to the Goddess of knowledge' },
      { step: 6, name: 'Aarti', icon: '🪔', duration: 20, mantra: 'Jai Saraswati Mata, Maiyya Jai Saraswati Mata, Sadgun Vaibhav Shalini, Tribhuvan Vidhata', meaning: 'Waving the lamp before the divine Goddess of learning' },
      { step: 7, name: 'Visarjana', icon: '✨', duration: 15, mantra: 'Om Aim Sarasvatyai Namaha — Vidya Vidya Saraswati', meaning: 'Receiving the Goddess\'s blessings of knowledge and creativity' },
    ],
    famousTemples: ['Gnana Saraswati Basar Telangana', 'Saraswati Mandir Pushkar', 'Koothanur Saraswati Tamil Nadu'],
  },

  {
    id: 'krishna',
    name: 'Lord Krishna',
    sanskrit: 'ॐ नमो भगवते वासुदेवाय',
    title: 'Yogeshvara – Master of All Yoga & Divine Love',
    emoji: '🦚',
    color: '#00897B',
    gradient: 'linear-gradient(135deg, #004D40, #00897B)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Krishna_and_Radha.jpg/400px-Krishna_and_Radha.jpg',
    blessings: ['Divine Love & Joy', 'Wisdom (Gita)', 'Children & Family', 'Music & Arts', 'Yogic Guidance'],
    goodDays: ['Wednesday', 'Janmashtami', 'Ekadashi', 'Purnima'],
    goodNakshatras: ['Rohini', 'Dhanishtha', 'Shravana'],
    avoidDays: [],
    avoidTithi: [],
    primaryMantra: 'Om Namo Bhagavate Vasudevaya',
    moola: 'ॐ नमो भगवते वासुदेवाय',
    dhyana: 'Om Krishnaya Vidmahe Vasudevaya Dhimahi Tanno Krishna Prachodayat',
    gayatri: 'Om Krishnaya Vidmahe Vasudevaya Dhimahi Tanno Krishna Prachodayat',
    offerings: [
      { name: 'Makhan (Butter)', icon: '🧈', mantra: 'Om Krishnaya Namaha — Navanitam Samarpayami' },
      { name: 'Tulsi', icon: '🌿', mantra: 'Om Vasudevaya Namaha — Tulasim Samarpayami' },
      { name: 'Yellow Flowers', icon: '🌼', mantra: 'Om Govindaya Namaha — Pushpam Samarpayami' },
      { name: 'Flute Offering', icon: '🎶', mantra: 'Om Gopala Krishnaya Namaha — Vamsham Samarpayami' },
      { name: 'Panchamruta', icon: '🥛', mantra: 'Om Madhavaya Namaha — Panchamrutam Samarpayami' },
    ],
    ashtottara: [
      'Om Krishnaya Namaha','Om Keshavaya Namaha','Om Govindaya Namaha',
      'Om Vasudevaya Namaha','Om Jagannathaya Namaha','Om Purushottamaya Namaha',
      'Om Madhavaya Namaha','Om Mukundaya Namaha','Om Acyutaya Namaha',
      'Om Gopaalaya Namaha','Om Damodaraya Namaha','Om Balabhadraya Namaha',
    ],
    archanaSequence: [
      { step: 1, name: 'Panchamruta', icon: '🥛', duration: 25, mantra: 'Om Krishnaya Namaha — Panchamrutam Samarpayami', meaning: 'Bathing Lord Krishna with milk, curd, honey, ghee and sugar' },
      { step: 2, name: 'Sankalpa', icon: '🙏', duration: 30, mantra: '(Name, gotra) ...Krishna prasada siddhyartham archana karishye', meaning: 'Entering the divine playfield of Lord Krishna with devotion' },
      { step: 3, name: 'Dhyana', icon: '🧘', duration: 20, mantra: 'Meditate: A blue-hued Lord, flute in hand, peacock feather adorning his crown, Radha by his side', meaning: 'Meditating on Krishna — the divine beloved who steals all hearts' },
      { step: 4, name: 'Tulsi Archana', icon: '🌿', duration: 40, mantra: 'Om Namo Bhagavate Vasudevaya — Tulasim Samarpayami (108 times)', meaning: 'Offering 108 Tulsi leaves — Krishna\'s most beloved offering' },
      { step: 5, name: 'Bhagavad Gita Shloka', icon: '📖', duration: 40, mantra: 'Yada Yada Hi Dharmasya Glanir Bhavati Bharata, Abhyutthanam Adharmasya Tadatmanam Srijamyaham', meaning: 'Reciting the divine promise of the Lord from the Bhagavad Gita' },
      { step: 6, name: 'Aarti', icon: '🪔', duration: 20, mantra: 'Aarti Kunj Bihari Ki, Shri Girdhar Krishna Murari Ki', meaning: 'Waving the golden lamp before the playful Lord of Vrindavan' },
      { step: 7, name: 'Visarjana', icon: '✨', duration: 15, mantra: 'Hare Krishna Hare Krishna Krishna Krishna Hare Hare, Hare Rama Hare Rama Rama Rama Hare Hare', meaning: 'Receiving Krishna\'s blessings with the divine Maha Mantra' },
    ],
    famousTemples: ['Vrindavan Banke Bihari', 'Guruvayur Kerala', 'Udupi Krishna Karnataka'],
  },

  {
    id: 'murugan',
    name: 'Lord Murugan',
    sanskrit: 'ॐ शरवणभव',
    title: 'Karthikeya – God of War, Victory & Wisdom',
    emoji: '⚡',
    color: '#AD1457',
    gradient: 'linear-gradient(135deg, #880E4F, #AD1457)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Murugan_idol_at_Palani.jpg/400px-Murugan_idol_at_Palani.jpg',
    blessings: ['Victory in Battle', 'Youth & Energy', 'Wisdom', 'Spiritual Power', 'Destroy Ego'],
    goodDays: ['Tuesday', 'Friday', 'Skanda Sashti', 'Thaipusam', 'Krittika Nakshatra day'],
    goodNakshatras: ['Krittika', 'Vishakha', 'Chitra'],
    avoidDays: [],
    avoidTithi: [],
    primaryMantra: 'Om Sharavanabhava',
    moola: 'ॐ शरवणभव',
    dhyana: 'Om Tathapurushaaya Vidmahe Mahasenanaya Dhimahi Tanno Skandha Prachodayat',
    gayatri: 'Om Tathapurushaaya Vidmahe Mahasenanaya Dhimahi Tanno Skandha Prachodayat',
    offerings: [
      { name: 'Red Flowers', icon: '🌺', mantra: 'Om Muruganaya Namaha — Rakta Pushpam Samarpayami' },
      { name: 'Vel (Spear)', icon: '⚡', mantra: 'Om Kumaaraya Namaha — Shaktim Samarpayami' },
      { name: 'Fruits', icon: '🍇', mantra: 'Om Shanmukhaya Namaha — Phalam Samarpayami' },
      { name: 'Peacock Feather', icon: '🦚', mantra: 'Om Shikhivahanaya Namaha — Mayura Punchham Samarpayami' },
      { name: 'Honey', icon: '🍯', mantra: 'Om Karthikeyaya Namaha — Madhu Samarpayami' },
    ],
    ashtottara: [
      'Om Skandaya Namaha','Om Karthikeyaya Namaha','Om Kumaaraya Namaha',
      'Om Shanmukhaya Namaha','Om Shikhivahanaya Namaha','Om Brahmasutaya Namaha',
      'Om Gaangeyaya Namaha','Om Subramanyaya Namaha','Om Shaktidharaya Namaha',
      'Om Surasenanyai Namaha','Om Vignesha Sahodharaya Namaha','Om Sharavanabhavaya Namaha',
    ],
    archanaSequence: [
      { step: 1, name: 'Achamana', icon: '💧', duration: 15, mantra: 'Om Shanmukhaya Namaha — Achamanam Samarpayami', meaning: 'Purification before the six-faced warrior God' },
      { step: 2, name: 'Sankalpa', icon: '🙏', duration: 30, mantra: '(Name, gotra) ...Murugan prasada siddhyartham archana karishye', meaning: 'Seeking victory and wisdom from Lord Murugan' },
      { step: 3, name: 'Thiruppugazh Recitation', icon: '📖', duration: 60, mantra: 'Thiruppugazh — sacred hymns of Arunagirinathar to Lord Murugan', meaning: 'Reciting the divine praises of Murugan from Thiruppugazh' },
      { step: 4, name: 'Vel Puja', icon: '⚡', duration: 30, mantra: 'Om Sharavanabhava — Vel Vel Muruga Vel', meaning: 'Worshipping Murugan\'s Vel — the divine spear of spiritual victory' },
      { step: 5, name: 'Flower Archana', icon: '🌺', duration: 40, mantra: 'Om Karthikeyaya Namaha — Pushpam Samarpayami (108 times)', meaning: 'Offering 108 red flowers to the eternal youth' },
      { step: 6, name: 'Aarti', icon: '🪔', duration: 20, mantra: 'Vel Vel Vel Vel, Muruga Vel Vel, Sakthi Vel Vel, Gnana Vel Vel', meaning: 'Waving the lamp before the son of Shiva and Parvati' },
      { step: 7, name: 'Visarjana', icon: '✨', duration: 15, mantra: 'Om Sharavanabhava — Om Om Muruga Namaha', meaning: 'Receiving Murugan\'s blessings of courage and divine wisdom' },
    ],
    famousTemples: ['Palani Murugan Tamil Nadu', 'Tirupparankundram', 'Pazhani Murugan'],
  },

  {
    id: 'surya',
    name: 'Lord Surya',
    sanskrit: 'ॐ घृणिः सूर्याय नमः',
    title: 'Aditya – The Eternal Sun, Source of All Life',
    emoji: '☀️',
    color: '#F57F17',
    gradient: 'linear-gradient(135deg, #E65100, #F57F17)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Konark_Sun_Temple.jpg/400px-Konark_Sun_Temple.jpg',
    blessings: ['Health & Vitality', 'Success & Fame', 'Eye Health', 'Leadership', 'Remove Diseases'],
    goodDays: ['Sunday', 'Saptami (7th Tithi)', 'Ratha Saptami', 'Makar Sankranti'],
    goodNakshatras: ['Krittika', 'Uttara Phalguni', 'Uttara Ashadha'],
    avoidDays: [],
    avoidTithi: [],
    primaryMantra: 'Om Hraam Hreem Hraum Sah Suryaya Namaha',
    moola: 'ॐ घृणिः सूर्याय नमः',
    dhyana: 'Om Aashakraya Vidmahe Diva Karaya Dhimahi Tanno Surya Prachodayat',
    gayatri: 'Om Bhaskaraya Vidmahe Mahadyutikaraya Dhimahi Tanno Adityah Prachodayat',
    offerings: [
      { name: 'Red Lotus', icon: '🌹', mantra: 'Om Suryaya Namaha — Raktapushpam Samarpayami' },
      { name: 'Wheat & Jaggery', icon: '🌾', mantra: 'Om Adityaya Namaha — Godhuma Samarpayami' },
      { name: 'Water Arghya', icon: '💧', mantra: 'Om Bhaskaraya Namaha — Arghyam Samarpayami' },
      { name: 'Red Cloth', icon: '🟥', mantra: 'Om Vivasvatay Namaha — Vastram Samarpayami' },
      { name: 'Copper Vessel', icon: '🏺', mantra: 'Om Savitray Namaha — Tamarapaatraam Samarpayami' },
    ],
    ashtottara: [
      'Om Suryaya Namaha','Om Archanaya Namaha','Om Bhaskaraya Namaha',
      'Om Aditya Namaha','Om Sahasramsave Namaha','Om Prabhakara Namaha',
      'Om Bhanu Namaha','Om Saptasva Namaha','Om Savitray Namaha',
      'Om Ravi Namaha','Om Padmaprabha Namaha','Om Vivasvate Namaha',
    ],
    archanaSequence: [
      { step: 1, name: 'Pratar Arghya', icon: '💧', duration: 20, mantra: 'Om Hraam Hreem Hraum Sah Suryaya Namaha — Arghyam Samarpayami', meaning: 'Offering water to the rising sun — the most powerful solar prayer' },
      { step: 2, name: 'Sankalpa', icon: '🙏', duration: 30, mantra: '(Name, gotra) ...Surya Deva prasada siddhyartham archana karishye', meaning: 'Seeking the sun god\'s blessings of health and vitality' },
      { step: 3, name: 'Aditya Hridayam', icon: '📖', duration: 90, mantra: 'Adi Deva Namastubhyam Prasida Mama Bhaskara, Divakara Namastubhyam Prabhakara Namostute', meaning: 'Reciting Aditya Hridayam — Agastya Muni\'s prayer that gave Rama victory' },
      { step: 4, name: 'Red Lotus Archana', icon: '🌹', duration: 40, mantra: 'Om Suryaya Namaha — Pushpam Samarpayami (108 times)', meaning: 'Offering 108 red lotus petals to the life-giving sun' },
      { step: 5, name: 'Surya Namaskar Mantra', icon: '🌅', duration: 30, mantra: 'Om Mitraya Namaha, Om Ravaye Namaha, Om Suryaya Namaha...', meaning: 'Reciting the 12 names of Surya as part of Surya Namaskar' },
      { step: 6, name: 'Deepa Aarti', icon: '🪔', duration: 20, mantra: 'Jai Jai Jagatpati, Jai Divakara Hai, Jai Jai Surya Deva', meaning: 'Waving the lamp before the eternal light of the universe' },
      { step: 7, name: 'Visarjana', icon: '✨', duration: 15, mantra: 'Om Hraam Hreem Hraum Sah Suryaya Namaha — Jai Surya Deva', meaning: 'Receiving Surya\'s blessings of radiant health and success' },
    ],
    famousTemples: ['Konark Sun Temple Odisha', 'Modhera Sun Temple Gujarat', 'Suryanar Koil Tamil Nadu'],
  },

  {
    id: 'saibaba',
    name: 'Shirdi Sai Baba',
    sanskrit: 'ॐ साईं नाथाय नमः',
    title: 'Sabka Malik Ek – Universal Spiritual Master',
    emoji: '🕊️',
    color: '#4CAF50',
    gradient: 'linear-gradient(135deg, #1B5E20, #4CAF50)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Sai_Baba_of_Shirdi.jpg/400px-Sai_Baba_of_Shirdi.jpg',
    blessings: ['All Wishes Fulfilled', 'Faith & Patience', 'Healing', 'Family Harmony', 'Remove Sorrow'],
    goodDays: ['Thursday', 'Guru Purnima', 'Sai Baba Jayanti', 'Datta Jayanti'],
    goodNakshatras: ['Punarvasu', 'Pushya', 'Anuradha'],
    avoidDays: [],
    avoidTithi: [],
    primaryMantra: 'Om Sai Nathaya Namaha',
    moola: 'ॐ साईं नाथाय नमः',
    dhyana: 'Samastha Lokah Sukhino Bhavantu — Sabka Malik Ek',
    gayatri: 'Om Shirdi Vasaya Vidmahe Satchidanandaya Dhimahi Tanno Sai Prachodayat',
    offerings: [
      { name: 'Green Flowers', icon: '🌿', mantra: 'Om Sai Nathaya Namaha — Pushpam Samarpayami' },
      { name: 'Udi (Sacred Ash)', icon: '🌫️', mantra: 'Om Shirdi Vasaya Namaha — Udim Samarpayami' },
      { name: 'Coconut', icon: '🥥', mantra: 'Om Satchidanandaya Namaha — Narikela Samarpayami' },
      { name: 'Dakshina', icon: '🪙', mantra: 'Om Sai Guruve Namaha — Dakshinam Samarpayami' },
      { name: 'Incense', icon: '🌫️', mantra: 'Om Antaryamine Namaha — Dhoopam Samarpayami' },
    ],
    ashtottara: [
      'Om Sai Nathaya Namaha','Om Lakshmi Narayan Swaroopaya Namaha','Om Krishnaramashivaya Namaha',
      'Om Shirdi Vasaya Namaha','Om Bhakta Vatsalaya Namaha','Om Satchidanandaya Namaha',
      'Om Sarva Hrit Sthitaya Namaha','Om Sarvabhishta Pradaaya Namaha','Om Anantaya Namaha',
      'Om Anandaya Namaha','Om Datta Treya Swaroopaya Namaha','Om Sai Devaaya Namaha',
    ],
    archanaSequence: [
      { step: 1, name: 'Diya Lighting', icon: '🪔', duration: 15, mantra: 'Om Sai Nathaya Namaha — Dipam Samarpayami', meaning: 'Lighting the sacred lamp as Sai Baba instructed all devotees' },
      { step: 2, name: 'Sankalpa', icon: '🙏', duration: 30, mantra: '(Name) ...Sai Baba prasada siddhyartham archana karishye — Sabka Malik Ek', meaning: 'Surrendering completely to Sai Baba\'s divine will' },
      { step: 3, name: 'Sai Baba Stavan', icon: '📖', duration: 60, mantra: 'Sai Baba Charitra — Ananta Koti Brahmanda Nayaka Rajadhi Raja Yogiraja', meaning: 'Reciting the sacred praises of Shirdi Sai Baba' },
      { step: 4, name: 'Flower Archana', icon: '🌿', duration: 40, mantra: 'Om Sai Nathaya Namaha — Pushpam Samarpayami (108 times)', meaning: 'Offering 108 flowers with complete surrender and faith' },
      { step: 5, name: 'Sai Satcharitra Reading', icon: '📚', duration: 30, mantra: 'He Sai Bhagwan Mere Sar Pe Hath Rakho, Meri Nao Bhi Paar Karo', meaning: 'Reading from Sai Satcharitra — the most blessed practice for devotees' },
      { step: 6, name: 'Udi Prasad', icon: '🌫️', duration: 20, mantra: 'Om Sai Nathaya Namaha — Udim Grihana', meaning: 'Receiving the sacred Udi (ash) — Sai\'s most powerful blessing' },
      { step: 7, name: 'Visarjana', icon: '✨', duration: 15, mantra: 'Om Sai Ram, Sai Ram, Sai Ram — Sabka Malik Ek Hai', meaning: 'Receiving Sai Baba\'s blessing: "Shraddha and Saburi — Faith and Patience"' },
    ],
    famousTemples: ['Shirdi Sai Temple Maharashtra', 'Sai Baba Temple Puttaparthi', 'All Sai Mandirs worldwide'],
  },
];

// Panchang-based auspicious day calculator per deity
function isGoodDayForGod(god, date) {
  const day = date.toLocaleDateString('en-US', { weekday: 'long' });
  return god.goodDays.some(d => d.toLowerCase().includes(day.toLowerCase()));
}

// Export for use in other scripts
if (typeof module !== 'undefined') module.exports = { GODS };
